/* Generated by wayland-scanner 1.23.1 */

/*
 * Copyright © 2012 Intel Corporation
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

#ifndef __has_attribute
# define __has_attribute(x) 0  /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#define WL_PRIVATE __attribute__ ((visibility("hidden")))
#else
#define WL_PRIVATE
#endif

extern const struct wl_interface wl_surface_interface;

static const struct wl_interface *weston_test_types[] = {
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	&wl_surface_interface,
	NULL,
	NULL,
	&wl_surface_interface,
};

static const struct wl_message weston_test_requests[] = {
	{ "move_surface", "oii", weston_test_types + 7 },
	{ "move_pointer", "uuuii", weston_test_types + 0 },
	{ "send_button", "uuuiu", weston_test_types + 0 },
	{ "send_axis", "uuuuf", weston_test_types + 0 },
	{ "activate_surface", "?o", weston_test_types + 10 },
	{ "send_key", "uuuuu", weston_test_types + 0 },
	{ "device_release", "s", weston_test_types + 0 },
	{ "device_add", "s", weston_test_types + 0 },
	{ "send_touch", "uuuiffu", weston_test_types + 0 },
	{ "client_break", "uu", weston_test_types + 0 },
};

static const struct wl_message weston_test_events[] = {
	{ "pointer_position", "ff", weston_test_types + 0 },
};

WL_PRIVATE const struct wl_interface weston_test_interface = {
	"weston_test", 1,
	10, weston_test_requests,
	1, weston_test_events,
};

static const struct wl_message weston_test_runner_requests[] = {
	{ "destroy", "", weston_test_types + 0 },
	{ "run", "s", weston_test_types + 0 },
};

static const struct wl_message weston_test_runner_events[] = {
	{ "finished", "", weston_test_types + 0 },
};

WL_PRIVATE const struct wl_interface weston_test_runner_interface = {
	"weston_test_runner", 1,
	2, weston_test_runner_requests,
	1, weston_test_runner_events,
};

