/* Generated by wayland-scanner 1.23.1 */

/*
 * Copyright 2020, 2022 Collabora, Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

#ifndef __has_attribute
# define __has_attribute(x) 0  /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#define WL_PRIVATE __attribute__ ((visibility("hidden")))
#else
#define WL_PRIVATE
#endif

extern const struct wl_interface weston_capture_source_v1_interface;
extern const struct wl_interface wl_buffer_interface;
extern const struct wl_interface wl_output_interface;

static const struct wl_interface *weston_output_capture_types[] = {
	NULL,
	NULL,
	&wl_output_interface,
	NULL,
	&weston_capture_source_v1_interface,
	&wl_buffer_interface,
};

static const struct wl_message weston_capture_v1_requests[] = {
	{ "destroy", "", weston_output_capture_types + 0 },
	{ "create", "oun", weston_output_capture_types + 2 },
};

WL_PRIVATE const struct wl_interface weston_capture_v1_interface = {
	"weston_capture_v1", 1,
	2, weston_capture_v1_requests,
	0, NULL,
};

static const struct wl_message weston_capture_source_v1_requests[] = {
	{ "destroy", "", weston_output_capture_types + 0 },
	{ "capture", "o", weston_output_capture_types + 5 },
};

static const struct wl_message weston_capture_source_v1_events[] = {
	{ "format", "u", weston_output_capture_types + 0 },
	{ "size", "ii", weston_output_capture_types + 0 },
	{ "complete", "", weston_output_capture_types + 0 },
	{ "retry", "", weston_output_capture_types + 0 },
	{ "failed", "?s", weston_output_capture_types + 0 },
};

WL_PRIVATE const struct wl_interface weston_capture_source_v1_interface = {
	"weston_capture_source_v1", 1,
	2, weston_capture_source_v1_requests,
	5, weston_capture_source_v1_events,
};

