CAPNPROTO_INSTALL_ROOT := $(QNX_HOST)

CMAKE_ARGS += -DCMAKE_INSTALL_PREFIX=$(CAPNPROTO_INSTALL_ROOT)/usr \
              -DINCLUDE_INSTALL_DIR=$(CAPNPROTO_INSTALL_ROOT)/usr/include \
              -DCMAKE_PREFIX_PATH=$(CAPNPROTO_INSTALL_ROOT) \
