#!/bin/sh

NESTED_LEVEL="${QNX_PROJECT_ROOT:-../../..}"  
BASIC_PREFIX="/usr/local"
EXEC_PREFIX="/${cpudir}${BASIC_PREFIX}"

function hook_preconfigure {
    cd "${QNX_PROJECT_ROOT}" || exit 1
    if [ -f "./autogen.sh" ]; then
        echo "hook_preconfigure - running autogen.sh in ${NESTED_LEVEL}"
        ./autogen.sh || exit 1
    fi

    unset AUTOMAKE AUTOCONF AUTOHEADER AUTORECONF ACLOCAL
    export DESTDIR="${INSTALL_ROOT_nto}"
    export CPPFLAGS="-I$QNX_TARGET${BASIC_PREFIX}/include/" 
    export LDFLAGS="-L$QNX_TARGET/${cpudir}${BASIC_PREFIX}/lib -lsocket -lnettle -lgmp -lm -Wl,-rpath-link,$QNX_TARGET/${cpudir}${BASIC_PREFIX}/lib"
    export PKG_CONFIG_LIBDIR="$QNX_TARGET/${cpudir}${BASIC_PREFIX}/lib/pkgconfig"

}

function hook_configure {
    echo "hook_configure - CC=$CC"
    cd "${QNX_PROJECT_ROOT}" || exit 1
    
    # Standard Autoconf + Chrony options + let build-cfg pass --host/--build
    "${QNX_PROJECT_ROOT}/configure" \
        --enable-ntp-signd \
        --host-system=QNX \
        --prefix=${BASIC_PREFIX} \
        --exec-prefix=${EXEC_PREFIX} \
        "$@" \
        || exit 1
}

function hook_make {
    echo "hook_make - running make ${make_cmds}"

    INSTALL_ROOT="${INSTALL_ROOT_nto}"
    FixMakeEnvironment

    if [ "${make_cmds}" = "install" ]; then
        make ${JLEVEL:+-j${JLEVEL}} install DESTDIR="${INSTALL_ROOT}" || exit 1
        find ${INSTALL_ROOT_nto} -name "*.la" -exec rm -f {} \;
    else
        make ${JLEVEL:+-j${JLEVEL}} ${make_cmds} || exit 1
    fi
}
