#!/bin/sh

function hook_configure {
    ${QNX_PROJECT_ROOT}/configure \
    --prefix=${INSTALL_ROOT}/${cpudir}/usr/local \
    --includedir=${INSTALL_ROOT}/usr/local/include \
    --host=${machine}
}
