#!/bin/sh

function hook_configure {

	: "${QNX_PROJECT_ROOT:="$(pwd)/../../../../zstd"}"

	echo "Copying source into $(pwd) ..."
	rsync -r --exclude=.git --exclude=.github --exclude=qnx "${QNX_PROJECT_ROOT}/" .

}

function hook_make {

	MAKEDIR="lib"
	TARGETS="lib-release"
	TARGETS_INSTALL="install"
	EXAMPLES_DIR="examples"

	export DESTDIR=${INSTALL_ROOT_nto}
	export PREFIX="/usr/local"
	export EXEC_PREFIX=/${cpudir}/${PREFIX}

	if [ "${make_cmds}" == "install" ]; then

	make -C ${MAKEDIR} -fMakefile \
		${make_CC:+"CC=${make_CC}"} \
		${make_defns} \
		${ac_autotools} \
		${make_opts} \
		${JLEVEL:+"-j${JLEVEL}"} ${TARGETS} ${TARGETS_INSTALL}\
		|| exit;

	else
	make -C ${MAKEDIR} -fMakefile \
		${make_CC:+"CC=${make_CC}"} \
		${make_defns} \
		${ac_autotools} \
		${make_opts} \
		${make_cmds} \
		${JLEVEL:+"-j${JLEVEL}"} \
		|| exit;
	fi

	# Building examples
	make -C ${EXAMPLES_DIR} -fMakefile \
		${make_CC:+"CC=${make_CC}"} \
		${make_defns} \
		${ac_autotools} \
		${make_opts} \
		${JLEVEL:+"-j${JLEVEL}"} \
		|| exit
}

function hook_postmake {
	base_build=$PWD
	base_prefix="/usr/local"
	base_examples_dir=${base_build}/examples
	install_examples_dir=${INSTALL_ROOT_nto}/${cpudir}/${base_prefix}/examples

	[ -d "${install_examples_dir}" ] || (set -x; mkdir -p ${install_examples_dir})

	if [ "${make_cmds}" == "install" ]; then
		echo "installing examples"
		(set -x; find ${base_examples_dir} -type f -executable -exec cp -f {} ${install_examples_dir} \;)
	fi
}
