/* Generated by wayland-scanner 1.23.1 */

/*
 * Copyright 2017-2018 Collabora, Ltd.
 * Copyright 2017-2018 General Electric Company
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

#ifndef __has_attribute
# define __has_attribute(x) 0  /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#define WL_PRIVATE __attribute__ ((visibility("hidden")))
#else
#define WL_PRIVATE
#endif

extern const struct wl_interface weston_touch_calibrator_interface;
extern const struct wl_interface weston_touch_coordinate_interface;
extern const struct wl_interface wl_surface_interface;

static const struct wl_interface *weston_touch_calibration_types[] = {
	NULL,
	NULL,
	NULL,
	NULL,
	&wl_surface_interface,
	NULL,
	&weston_touch_calibrator_interface,
	NULL,
	NULL,
	&weston_touch_coordinate_interface,
};

static const struct wl_message weston_touch_calibration_requests[] = {
	{ "destroy", "", weston_touch_calibration_types + 0 },
	{ "create_calibrator", "osn", weston_touch_calibration_types + 4 },
	{ "save", "sa", weston_touch_calibration_types + 0 },
};

static const struct wl_message weston_touch_calibration_events[] = {
	{ "touch_device", "ss", weston_touch_calibration_types + 0 },
};

WL_PRIVATE const struct wl_interface weston_touch_calibration_interface = {
	"weston_touch_calibration", 1,
	3, weston_touch_calibration_requests,
	1, weston_touch_calibration_events,
};

static const struct wl_message weston_touch_calibrator_requests[] = {
	{ "destroy", "", weston_touch_calibration_types + 0 },
	{ "convert", "iin", weston_touch_calibration_types + 7 },
};

static const struct wl_message weston_touch_calibrator_events[] = {
	{ "configure", "ii", weston_touch_calibration_types + 0 },
	{ "cancel_calibration", "", weston_touch_calibration_types + 0 },
	{ "invalid_touch", "", weston_touch_calibration_types + 0 },
	{ "down", "uiuu", weston_touch_calibration_types + 0 },
	{ "up", "ui", weston_touch_calibration_types + 0 },
	{ "motion", "uiuu", weston_touch_calibration_types + 0 },
	{ "frame", "", weston_touch_calibration_types + 0 },
	{ "cancel", "", weston_touch_calibration_types + 0 },
};

WL_PRIVATE const struct wl_interface weston_touch_calibrator_interface = {
	"weston_touch_calibrator", 1,
	2, weston_touch_calibrator_requests,
	8, weston_touch_calibrator_events,
};

static const struct wl_message weston_touch_coordinate_events[] = {
	{ "result", "uu", weston_touch_calibration_types + 0 },
};

WL_PRIVATE const struct wl_interface weston_touch_coordinate_interface = {
	"weston_touch_coordinate", 1,
	0, NULL,
	1, weston_touch_coordinate_events,
};

