#!/bin/sh

# Control installation
DIST_BASE=${QNX_PROJECT_ROOT:-"${PWD}/../../../../vim"}
INSTALL_ROOT=$(eval "echo \${INSTALL_ROOT_${TARGET_SYSNAME}}")
PREFIX="/usr/local"

function hook_preconfigure
{
  # Override srcdir
  rm -rf ${PWD}/build
  mkdir -p ${PWD}/build
  cp -r ${DIST_BASE}/src build
  cp ${DIST_BASE}/README.txt build
  cp ${DIST_BASE}/LICENSE build
  export SRCDIR="${PWD}/build/src"
  configure_opts="$(echo ${configure_opts} | sed -e 's/--srcdir=..//')"

  # Installation locations
  configure_opts="${configure_opts} --srcdir=${SRCDIR}"
  configure_opts="${configure_opts} --prefix=${INSTALL_ROOT}/${PREFIX}"
  configure_opts="${configure_opts} --exec-prefix=${INSTALL_ROOT}/${cpudir}/${PREFIX}"

  # Set up options
  configure_opts="${configure_opts} --with-tlib=ncurses"
  configure_opts="${configure_opts} --enable-gui=no"

  # Set up runtime for installation
  ln -s ${DIST_BASE}/runtime build/runtime
  export STRIP="${machine}-strip"

}

# Override hook_configure to build from dist
# VIM doesn't want to be built outside of its source directory.
# To accomplish building for different targets we need to copy the source tree
# under the build directory.
function hook_configure
{
   cd $SRCDIR
   ./configure \
        ${ac_host:+"--host=${ac_host}"} \
        ${ac_build:+"--build=${ac_build}"} \
        ${configure_opts} \
        ${ac_params:+"vim_cv_toupper_broken=no"} \
        ${ac_params:+"vim_cv_terminfo=yes"} \
        ${ac_params:+"vim_cv_tgetent=0"} \
        ${ac_params:+"vim_cv_getcwd_broken=no"} \
        ${ac_params:+"vim_cv_timer_create=yes"} \
        ${ac_params:+"vim_cv_stat_ignores_slash=no"} \
        ${ac_params:+"vim_cv_memmove_handles_overlap=yes"} \
        ${ac_params:+"vim_cv_uname_output=QNX"} \
        ${ac_params:+${CC:+"CC=${CC}"}} \
        ${ac_params:+${CFLAGS:+"CFLAGS=${CFLAGS}"}} \
        ${ac_params:+${CPPFLAGS:+"CPPFLAGS=${CPPFLAGS}"}} \
        ${ac_params:+${LDFLAGS:+"LDFLAGS=${LDFLAGS}"}} \
        ${ac_params:+${CXX:+"CXX=${CXX}"}} \
        ${ac_params:+${CXXFLAGS:+"CXXFLAGS=${CXXFLAGS}"}} \
        ${ac_params:+${ac_autotools:+${ac_autotools}}} \
        || Error "configure failed";
}
