#!/bin/sh

project_dir="$(pwd)/../../../../atari800"

function hook_preconfigure {

		configure_opts="${configure_opts} --srcdir=${project_dir}"

		base_prefix="/usr/local"
		prefix="${INSTALL_ROOT_nto}/${base_prefix}"
		exec_prefix="${INSTALL_ROOT_nto}/${cpudir}/${base_prefix}"

		configure_opts="${configure_opts} --prefix=${prefix}"
		configure_opts="${configure_opts} --exec-prefix=${exec_prefix}"
		configure_opts="${configure_opts} --with-sysroot=${INSTALL_ROOT_nto}"
		configure_opts="${configure_opts} --with-sdl2-exec-prefix=${exec_prefix}"
		configure_opts="${configure_opts} --with-opengl=no"
		configure_opts="${configure_opts} --with-sound=no"

		# set flags
		CFLAGS="${CFLAGS} -g -O0"
		LDFLAGS="${LDFLAGS}"
}

function hook_configure {

		${project_dir}/configure \
		${ac_host:+"--host=${ac_host}"} \
		${ac_build:+"--build=${ac_build}"} \
		${configure_opts} \
		${ac_params:+${CC:+"CC=${CC}"}} \
		${ac_params:+${CFLAGS:+"CFLAGS=${CFLAGS}"}} \
		${ac_params:+${LDFLAGS:+"LDFLAGS=${LDFLAGS}"}} \
		${ac_params:+${ac_autotools:+${ac_autotools}}} \
		|| Error 'configure failed';
}
