/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define BINDIR "/data/home/qnxuser/bin"

#define BUILD_HEADLESS_COMPOSITOR 1

#define BUILD_QNX_SCREEN_COMPOSITOR 1

#define BUILD_WAYLAND_COMPOSITOR 1

#define DATADIR "/system/share"

#define EGL_NO_PLATFORM_SPECIFIC_TYPES 1

#define EGL_NO_X11 1

#define ENABLE_EGL 1

#define HAVE_INITGROUPS 1

#define HAVE_JPEG 1

#define HAVE_MKOSTEMP 1

#define HAVE_POSIX_FALLOCATE 1

#define HAVE_XKBCOMMON_COMPOSE 1

#define LIBEXECDIR "/data/home/qnxuser/lib/libexec"

#define LIBWESTON_MODULEDIR "/data/home/qnxuser/lib/libweston"

#define MAJOR_IN_SYSMACROS 1

#define MESA_EGL_NO_X11_HEADERS 1

#define MODULEDIR "/data/home/qnxuser/lib/weston"

#define PACKAGE_BUGREPORT "https://gitlab.freedesktop.org/wayland/weston/issues/"

#define PACKAGE_STRING "weston 11.0.0"

#define PACKAGE_URL "https://wayland.freedesktop.org"

#define PACKAGE_VERSION "11.0.0"

#define USE_RESIZE_POOL 1

#define VERSION "11.0.0"

#define WESTON_SHELL_CLIENT "weston-desktop-shell"

#define _ALL_SOURCE 1

#define _GNU_SOURCE 1

