/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define TESTSUITE_PLUGIN_PATH "/data/home/qnxuser/lib/test-plugin.so"

#define WESTON_DATA_DIR "/system/share/weston"

#define WESTON_MODULE_MAP \
    "color-lcms.so=/data/home/qnxuser/lib/libweston/color-lcms.so;" \
    "gl-renderer.so=/data/home/qnxuser/lib/libweston/gl-renderer.so;" \
    "drm-backend.so=/data/home/qnxuser/lib/libweston/drm-backend.so;" \
    "headless-backend.so=/data/home/qnxuser/lib/libweston/headless-backend.so;" \
    "wayland-backend.so=/data/home/qnxuser/lib/libweston/wayland-backend.so;" \
    "x11-backend.so=/data/home/qnxuser/lib/libweston/x11-backend.so;" \
    "screen-share.so=/data/home/qnxuser/lib/weston/screen-share.so;" \
    "desktop-shell.so=/data/home/qnxuser/lib/weston/desktop-shell.so;" \
    "ivi-shell.so=/data/home/qnxuser/lib/weston/ivi-shell.so;" \
    "hmi-controller.so=/data/home/qnxuser/lib/weston/hmi-controller.so;" \
    "kiosk-shell.so=/data/home/qnxuser/lib/weston/kiosk-shell.so;" \
    "weston-keyboard=/data/home/qnxuser/lib/libexec/weston-keyboard;" \
    "weston-screenshooter=/data/home/qnxuser/lib/libexec/weston-screenshooter;" \
    "weston-desktop-shell=/data/home/qnxuser/lib/libexec/weston-desktop-shell;" \
    "weston-ivi-shell-user-interface=/data/home/qnxuser/lib/libexec/weston-ivi-shell-user-interface;" \
    "weston-test-desktop-shell.so=/data/home/qnxuser/lib/weston-test-desktop-shell.so;" \
    "test-ivi-layout.so=/data/home/qnxuser/lib/test-ivi-layout.so;"

#define WESTON_TEST_REFERENCE_PATH "/data/home/qnxuser/reference"

#define WESTON_TEST_SKIP_IS_FAILURE 0

