name: abseil-cpp

permissions:
  contents: write
  checks: write
  issues: read

on:
  workflow_dispatch:
    inputs:
      requireRebuild:
        description: Require rebuild
        required: false
        default: false
        type: boolean
  push:
    branches:
      - main
    paths:
      - '.github/workflows/abseil-cpp.yml'
      - 'ports/abseil-cpp/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/abseil-cpp.yml'
      - 'ports/abseil-cpp/**'

jobs:

  build:
    strategy:
      matrix:
        qnx_env: ["710", "800"]
    runs-on: ubuntu-22.04-common
    if: |
      ((github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push') ||
      (github.event_name == 'pull_request'))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files

    - name: Checkout abseil-cpp
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/abseil-cpp
        path: abseil-cpp

    - name: Checkout muslflt
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/muslflt
        path: muslflt

    - name: Checkout googletest
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/googletest
        path: googletest

    - name: Checkout check-tools
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/check-tools
        path: check-tools
        ref: 752117d3e12f0ae53f7c3673696e171f9e0d5e7a


    - name: Checkout test-tools
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/test-tools
        path: test-tools
        token: ${{secrets.GCO_TOKEN}}

    - name: Attempt restore of runtime-deps
      if: |
        ${{(github.event_name != 'workflow_dispatch') ||
        !inputs.requireRebuild}}
      id: restore-stage
      uses: actions/cache/restore@v4
      env:
        cache-name: "abseil-cpp_20240116.0_${{ matrix.qnx_env }}"
      with:
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        path: |
          ${{ github.workspace }}/stage
          ${{ github.workspace }}/build-files

    - name: Build abseil-cpp
      if: ${{ steps.restore-stage.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        if [[ ${{ matrix.qnx_env }} == 800 ]]; then
          source ~/qnx/800/qnxsdp-env.sh
        else
          source ~/qnx/710/qnxsdp-env.sh
        fi
        cd ~/workspace
        if [[ ${{ matrix.qnx_env }} == 800 ]]; then
          touch build-files/ports/googletest/nto-arm-le-v7/Makefile.dnm
          touch build-files/ports/muslflt/nto-arm-le-v7/Makefile.dnm
          touch build-files/ports/abseil-cpp/nto-arm-le-v7/Makefile.dnm
        fi
        BUILD_TESTING="ON" QNX_PROJECT_ROOT="$(pwd)/googletest" make -C build-files/ports/googletest PREFIX=system INSTALL_ROOT_nto=$PWD/stage USE_INSTALL_ROOT=true install
        QNX_PROJECT_ROOT="$(pwd)/muslflt" make -C build-files/ports/muslflt/ PREFIX=system INSTALL_ROOT_nto=$PWD/stage USE_INSTALL_ROOT=true install
        QNX_SEVEN_COMPAT="true" BUILD_TESTING="ON" QNX_PROJECT_ROOT="$(pwd)/abseil-cpp" make -C build-files/ports/abseil-cpp PREFIX=system INSTALL_ROOT_nto=$PWD/stage USE_INSTALL_ROOT=true install

    - name: Cache runtime-deps
      if: ${{ (matrix.qnx_env == '800') }}
      uses: actions/cache/save@v4
      with:
        key: ${{ steps.restore-stage.outputs.cache-primary-key }}
        path: |
          ${{ github.workspace }}/stage
          ${{ github.workspace }}/build-files

    - name: Setup python env
      if: ${{ (matrix.qnx_env == '800') }}
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: pip install -r ./test-tools/requirements.txt

    - name: Test abseil-cpp
      if: ${{ (matrix.qnx_env == '800') }}
      env:
        OSS_NAME: "abseil-cpp"
        QNX_VERSION: "qnx${{ matrix.qnx_env }}"
        COMPANION_DIR: "${{ github.workspace }}/build-files/ports/abseil-cpp"
      shell: bash
      run: |
        source ~/qnx/800/qnxsdp-env.sh

        ./test-tools/bin/run_tests.sh

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v5
      if: ${{ always() }}
      with:
        report_paths: 'results/*.xml'
        comment: true
