name: abseil-cpp

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/abseil-cpp.yml'
      - 'ports/abseil-cpp/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/abseil-cpp.yml'
      - 'ports/abseil-cpp/**'

jobs:

  build:
    strategy:
      matrix:
        qnx_env: ["710", "800"]
    runs-on: self-hosted
    if: |
      (github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'abseil-cpp'))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files

    - name: Checkout abseil-cpp
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/abseil-cpp
        path: abseil-cpp

    - name: Checkout muslflt
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/muslflt
        path: muslflt

    - name: Checkout googletest
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/googletest
        path: googletest

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Pull build environment
      run: |
        docker pull ghcr.io/qnx-ports/sdp-build-env:latest

    - name: Build abseil-cpp
      uses: addnab/docker-run-action@v3
      with:
        image: ghcr.io/qnx-ports/sdp-build-env:latest
        options: -v ${{ github.workspace }}:/home/runner/workspace -e MAKEFLAGS=${{ env.MAKEFLAGS }}
        shell: bash
        run: |
          if [[ ${{ matrix.qnx_env }} == 800 ]]; then
            source ~/qnx/800/qnxsdp-env.sh
          else
            source ~/qnx/710/qnxsdp-env.sh
          fi
          cd ~/workspace
          if [[ ${{ matrix.qnx_env }} == 800 ]]; then
            touch build-files/ports/googletest/nto-arm-le-v7/Makefile.dnm
            touch build-files/ports/muslflt/nto-arm-le-v7/Makefile.dnm
            touch build-files/ports/abseil-cpp/nto-arm-le-v7/Makefile.dnm
          fi
          BUILD_TESTING="ON" QNX_PROJECT_ROOT="$(pwd)/googletest" make -C build-files/ports/googletest install
          QNX_PROJECT_ROOT="$(pwd)/muslflt" make -C build-files/ports/muslflt/ install
          BUILD_TESTING="ON" QNX_PROJECT_ROOT="$(pwd)/abseil-cpp" make -C build-files/ports/abseil-cpp install
