name: asio

permissions:
  contents: write
  checks: write
  issues: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/asio.yml'
      - 'ports/asio/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/asio.yml'
      - 'ports/asio/**'

jobs:

  build:
    runs-on: ubuntu-22.04-common
    if: |
      ((github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push') ||
      (github.event_name == 'pull_request'))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files

    - name: Checkout asio
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/asio
        path: asio

    - name: Build asio
      shell: bash
      run: |
        source ~/qnx/800/qnxsdp-env.sh
        cd asio/asio
        ./autogen.sh
        cd -
        make -C build-files/ports/asio install
