name: aws-c-common

permissions:
  contents: write
  checks: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/aws-c-common.yml"
      - "ports/aws-c-common/**"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/aws-c-common.yml"
      - "ports/aws-c-common/**"

jobs:
  build:
    strategy:
      matrix:
        qnx_env: ["710", "800"]
      fail-fast: false
    name: Build for QNX ${{ matrix.qnx_env }}
    runs-on: ubuntu-22.04-common
    if: |
      ((github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'aws-c-common')))
    steps:
      - name: Checkout build-files
        uses: actions/checkout@v4
        with:
          path: build-files

      - name: Checkout aws-c-common
        uses: actions/checkout@v4
        with:
          repository: qnx-ports/aws-c-common
          path: aws-c-common

      - name: Prepare QNX Software Center
        env:
          MYQNX_USER: ${{ secrets.MYQNX_USER }}
          MYQNX_PASSWORD: ${{ secrets.MYQNX_PASSWORD }}
        run: |
          echo "Downloading QNX Software Center ..."
          mkdir ${{ github.workspace }}/.qnx
          curl -v --cookie-jar ${{ github.workspace }}/.qnx/myqnxcookies.auth --form "userlogin=$MYQNX_USER" --form "password=$MYQNX_PASSWORD" -X POST https://www.qnx.com/account/login.html > login_response.html
          curl -v -L --cookie ${{ github.workspace }}/.qnx/myqnxcookies.auth https://www.qnx.com/download/download/77351/qnx-setup-2.0.3-202408131717-linux.run > qnx-setup-lin.run
          chmod a+x qnx-setup-lin.run
          ./qnx-setup-lin.run force-override disable-auto-start agree-to-license-terms ${{ github.workspace }}/qnx

      - name: Activate 710 license
        env:
          MYQNX_USER: ${{ secrets.MYQNX_USER }}
          MYQNX_PASSWORD: ${{ secrets.MYQNX_PASSWORD }}
        run: |
          echo "Activating keys..."
          ${{ github.workspace }}/qnx/qnxsoftwarecenter/qnxsoftwarecenter_clt qnxsoftwarecenter_clt -activateAll --myqnx.user="$MYQNX_USER" -myqnx.password="$MYQNX_PASSWORD"

      - name: Build aws-c-common
        shell: bash
        run: |
          if [[ ${{ matrix.qnx_env }} == 710 ]]; then
            source ~/qnx/710/qnxsdp-env.sh
          else
            source ~/qnx/800/qnxsdp-env.sh
          fi
          cd ~
          ls qnx
          echo -e '#include <stdio.h>\nint main() { printf("Hello, World!\\n"); return 0; }' > hello.c
          qcc hello.c -o hello
