name: aws-c-io

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/aws-c-io.yml"
      - "ports/aws-c-io/**"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/aws-c-io.yml"
      - "ports/aws-c-io/**"

jobs:
  build:
    strategy:
      matrix:
        qnx_env: ["710", "800"]
    name: Build for QNX ${{ matrix.qnx_env }}
    runs-on: self-hosted
    if: |
      (github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'aws-c-io'))
    steps:
      - name: Checkout build-files
        uses: actions/checkout@v4
        with:
          path: build-files

      - name: Checkout aws-c-common
        uses: actions/checkout@v4
        with:
          repository: qnx-ports/aws-c-common
          path: aws-c-common

      - name: Checkout aws-c-cal
        uses: actions/checkout@v4
        with:
          repository: awslabs/aws-c-cal
          path: aws-c-cal

      - name: Checkout s2n-tls
        uses: actions/checkout@v4
        with:
          repository: qnx-ports/s2n-tls
          path: s2n-tls

      - name: Checkout aws-c-io
        uses: actions/checkout@v4
        with:
          repository: qnx-ports/aws-c-io
          path: aws-c-io

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Pull build environment
        run: |
          docker pull ghcr.io/qnx-ports/sdp-build-env:latest

      - name: Build aws-c-io
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/qnx-ports/sdp-build-env:latest
          options: -v ${{ github.workspace }}:/home/runner/workspace -e MAKEFLAGS=${{ env.MAKEFLAGS }}
          shell: bash
          run: |
            if [[ ${{ matrix.qnx_env }} == 710 ]]; then
              source ~/qnx/710/qnxsdp-env.sh
            else
              source ~/qnx/800/qnxsdp-env.sh
            fi
            cd ~/workspace
            make -C build-files/ports/aws-c-common install
            make -C build-files/ports/s2n-tls install
            make -C build-files/ports/aws-c-cal install
            make -C build-files/ports/aws-c-io install
