name: azure-iot-sdk-c

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/azure-iot-sdk-c.yml'
      - 'ports/azure-iot-sdk-c/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/azure-iot-sdk-c.yml'
      - 'ports/azure-iot-sdk-c/**'

jobs:

  build:
    runs-on: self-hosted
    if: |
      (github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'azure-iot-sdk-c'))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files

    - name: Checkout azure-iot-sdk-c
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/azure-iot-sdk-c
        path: azure-iot-sdk-c
        submodules: recursive

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Pull build environment
      run: |
        docker pull ghcr.io/qnx-ports/sdp800-build-env:latest

    - name: Build azure-iot-sdk
      uses: addnab/docker-run-action@v3
      with:
        image: ghcr.io/qnx-ports/sdp800-build-env:latest
        options: -v ${{ github.workspace }}:/home/runner/workspace -e MAKEFLAGS=${{ env.MAKEFLAGS }}
        shell: bash
        run: |
          source ~/qnx/800/qnxsdp-env.sh
          cd ~/workspace
          WORKSPACE=$PWD
          cd $WORKSPACE/build-files/ports/azure-iot-sdk-c
          ./scripts/patch.sh $WORKSPACE/azure-iot-sdk-c
          cd $WORKSPACE
          QNX_PROJECT_ROOT="$(pwd)/azure-iot-sdk-c" make -C build-files/ports/azure-iot-sdk-c install
