name: bzip2

permissions:
  contents: write
  checks: write

 
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/bzip2.yml'
      - 'ports/bzip2/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/bzip2.yml'
      - 'ports/bzip2/**'

jobs:
 
  build:
    strategy:
      matrix:
        qnx_env: [710, 800]
    name: Build for QNX ${{ matrix.qnx_env }}
    runs-on: ubuntu-22.04-common
    if: |
      ((github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'bzip2')))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files
 
    - name: Checkout bzip2
      uses: actions/checkout@v4
      with:
        repository: libarchive/bzip2
        path: bzip2
        ref: bzip2-1.0.8
 
    - name: Build bzip2
      shell: bash
      run: |
        if [ "${{ matrix.qnx_env }}" == "710" ]; then
          source ~/qnx/710/qnxsdp-env.sh
        else
          source ~/qnx/800/qnxsdp-env.sh
        fi
        QNX_PROJECT_ROOT="$(pwd)/bzip2" JLEVEL=$(nproc) make -C build-files/ports/bzip2 install
