name: CANdb

permissions:
  contents: write
  checks: write


on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/CANdb.yml'
      - 'ports/CANdb/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/CANdb.yml'
      - 'ports/CANdb/**'

jobs:

  build:
    runs-on: ubuntu-22.04-common
    if: |
      ((github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'CANdb')))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files

    - name: Checkout CANdb
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/CANdb
        path: CANdb

    - name: Build CANdb
      shell: bash
      run: |
        source ~/qnx/800/qnxsdp-env.sh
        cd CANdb
        git submodule update --init --recursive
        cd -
        make -C build-files/ports/CANdb install
