name: capnproto

permissions:
  contents: write
  checks: write


on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/capnproto.yml'
      - 'ports/capnproto/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/capnproto.yml'
      - 'ports/capnproto/**'

jobs:

  build:
    runs-on: ubuntu-22.04-common
    if: |
      ((github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'capnproto')))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files

    - name: Checkout capnproto
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/capnproto
        path: capnproto

    - name: Checkout muslflt
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/muslflt
        path: muslflt

    - name: Build capnproto
      shell: bash
      run: |
        source ~/qnx/800/qnxsdp-env.sh
        QNX_PROJECT_ROOT="$(pwd)/muslflt" make -C build-files/ports/muslflt/ install
        BUILD_TESTING="ON" QNX_PROJECT_ROOT="$(pwd)/capnproto" make -C build-files/ports/capnproto install
