name: Catch2

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/Catch2.yml'
      - 'ports/Catch2/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/Catch2.yml'
      - 'ports/Catch2/**'

jobs:

  build:
    runs-on: self-hosted
    if: |
      (github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'Catch2'))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files

    - name: Checkout Catch2
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/Catch2
        path: Catch2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Pull build environment
      run: |
        docker pull ghcr.io/qnx-ports/sdp-build-env:latest

    - name: Build Catch2
      uses: addnab/docker-run-action@v3
      with:
        image: ghcr.io/qnx-ports/sdp-build-env:latest
        options: -v ${{ github.workspace }}:/home/runner/workspace -e MAKEFLAGS=${{ env.MAKEFLAGS }}
        shell: bash
        run: |
          source ~/qnx/800/qnxsdp-env.sh
          cd ~/workspace
          cd Catch2
          ./tools/scripts/generateAmalgamatedFiles.py
          cd -
          make -C build-files/ports/Catch2 install
