name: conan-catch2

permissions:
  contents: write
  checks: write


on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/conan-catch2.yml'
      - 'conan/recipes/catch2/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/conan-catch2.yml'
      - 'conan/recipes/catch2/**'

jobs:

  build:
    strategy:
      matrix:
        qnx_env: ["Linux", "QNX 710", "QNX 800"]
    name: Build conan catch2 for ${{ matrix.qnx_env }}
    runs-on: ubuntu-22.04-common
    if: |
      ((github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'conan')))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files

    - name: Build conan catch2 recipes
      shell: bash
      run: |
        python3.11 -m venv vpy
        . vpy/bin/activate
        pip install conan
        conan profile detect
        export QNX_CONAN_ROOT=$(realpath ./build-files/conan)
        conan config install $QNX_CONAN_ROOT/tools/qnx-8.0-extension/settings_user.yml
        if [ "${{ matrix.qnx_env }}" == "Linux" ]; then
          conan create --version=2.13.10 $QNX_CONAN_ROOT/recipes/catch2/2.x.x
          #conan create --version=3.6.0 $QNX_CONAN_ROOT/recipes/catch2/3.x.x
        elif [ "${{ matrix.qnx_env }}" == "QNX 710" ]; then
          source ~/qnx/710/qnxsdp-env.sh
          conan create -pr:h=$QNX_CONAN_ROOT/tools/profiles/nto-7.1-aarch64-le --version=2.13.10 $QNX_CONAN_ROOT/recipes/catch2/2.x.x
          conan create -pr:h=$QNX_CONAN_ROOT/tools/profiles/nto-7.1-aarch64-gcc --version=2.13.10 $QNX_CONAN_ROOT/recipes/catch2/2.x.x
          conan create -pr:h=$QNX_CONAN_ROOT/tools/profiles/nto-7.1-x86_64 --version=2.13.10 $QNX_CONAN_ROOT/recipes/catch2/2.x.x
          conan create -pr:h=$QNX_CONAN_ROOT/tools/profiles/nto-7.1-x86_64-gcc --version=2.13.10 $QNX_CONAN_ROOT/recipes/catch2/2.x.x
        elif [ "${{ matrix.qnx_env }}" == "QNX 800" ]; then
          source ~/qnx/800/qnxsdp-env.sh
          conan create -pr:h=$QNX_CONAN_ROOT/tools/profiles/nto-8.0-aarch64-le --version=2.13.10 $QNX_CONAN_ROOT/recipes/catch2/2.x.x
          conan create -pr:h=$QNX_CONAN_ROOT/tools/profiles/nto-8.0-aarch64-gcc --version=2.13.10 $QNX_CONAN_ROOT/recipes/catch2/2.x.x
          conan create -pr:h=$QNX_CONAN_ROOT/tools/profiles/nto-8.0-x86_64 --version=2.13.10 $QNX_CONAN_ROOT/recipes/catch2/2.x.x
          conan create -pr:h=$QNX_CONAN_ROOT/tools/profiles/nto-8.0-x86_64-gcc --version=2.13.10 $QNX_CONAN_ROOT/recipes/catch2/2.x.x
        fi
