name: conan-gtest

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/conan-gtest.yml'
      - 'conan/recipes/gtest/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/conan-gtest.yml'
      - 'conan/recipes/gtest/**'

jobs:

  build:
    runs-on: self-hosted
    if: |
      (github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'conan'))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Pull build environment
      run: |
        docker pull ghcr.io/qnx-ports/sdp-build-env:latest

    - name: Build conan gtest recipes
      uses: addnab/docker-run-action@v3
      with:
        image: ghcr.io/qnx-ports/sdp-build-env:latest
        options: -v ${{ github.workspace }}:/home/runner/workspace -e MAKEFLAGS=${{ env.MAKEFLAGS }}
        shell: bash
        run: |
          cd ~/workspace
          python3.11 -m venv vpy
          . vpy/bin/activate
          pip install conan
          conan profile detect
          export QNX_CONAN_ROOT=$(realpath ./build-files/conan)
          conan config install $QNX_CONAN_ROOT/tools/qnx-8.0-extension/settings_user.yml
          source ~/qnx/800/qnxsdp-env.sh
          conan create -pr:h=$QNX_CONAN_ROOT/tools/profiles/nto-8.0-x86_64 --version=1.10.0 --build=missing $QNX_CONAN_ROOT/recipes/gtest/all
          conan create -pr:h=$QNX_CONAN_ROOT/tools/profiles/nto-8.0-x86_64 --version=1.13.0 --build=missing $QNX_CONAN_ROOT/recipes/gtest/all
          conan create -pr:h=$QNX_CONAN_ROOT/tools/profiles/nto-8.0-x86_64 --version=1.14.0 --build=missing $QNX_CONAN_ROOT/recipes/gtest/all
