name: dlt-daemon

permissions:
  contents: write
  checks: write


on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/dlt-daemon.yml'
      - 'ports/dlt-daemon/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/dlt-daemon.yml'
      - 'ports/dlt-daemon/**'

jobs:

  build:
    runs-on: ubuntu-22.04-common
    if: |
      (github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'dlt-daemon')))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files

    - name: Checkout dlt-daemon
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/dlt-daemon
        path: dlt-daemon
        submodules: 'true'

    - name: Build dlt-daemon
      shell: bash
      run: |
        source ~/qnx/800/qnxsdp-env.sh
        BUILD_TESTING="ON" QNX_PROJECT_ROOT="$(pwd)/dlt-daemon" make -C build-files/ports/dlt-daemon install

