name: dlt-daemon

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/dlt-daemon.yml'
      - 'ports/dlt-daemon/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/dlt-daemon.yml'
      - 'ports/dlt-daemon/**'

jobs:

  build:
    runs-on: self-hosted
    if: |
      (github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'dlt-daemon'))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files

    - name: Checkout dlt-daemon
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/dlt-daemon
        path: dlt-daemon
        submodules: 'true'

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Pull build environment
      run: |
        docker pull ghcr.io/qnx-ports/sdp800-build-env:latest

    - name: Build dlt-daemon
      uses: addnab/docker-run-action@v3
      with:
        image: ghcr.io/qnx-ports/sdp800-build-env:latest
        options: -v ${{ github.workspace }}:/home/runner/workspace -e MAKEFLAGS=${{ env.MAKEFLAGS }}
        shell: bash
        run: |
          source ~/qnx/800/qnxsdp-env.sh
          cd ~/workspace
          BUILD_TESTING="ON" QNX_PROJECT_ROOT="$(pwd)/dlt-daemon" make -C build-files/ports/dlt-daemon install

