name: EmulationStation

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/EmulationStation.yml'
      - 'ports/RetroPie/EmulationStation/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/EmulationStation.yml'
      - 'ports/RetroPie/EmulationStation/**'

jobs:

  build:
    runs-on: self-hosted
    if: |
      (github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && (contains(github.event.pull_request.title, 'EmulationStation')||contains(github.event.pull_request.title, 'Emulation Station')))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files

    - name: Checkout EmulationStation
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/EmulationStation
        path: EmulationStation
    
    - name: Checkout rapidjson
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/rapidjson
        path: rapidjson
    
    - name: Checkout SDL
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/SDL
        path: SDL

    - name: Checkout FreeImage
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/FreeImage
        path: FreeImage

    - name: Checkout pugixml
      uses: actions/checkout@v4
      with:
        repository: zeux/pugixml
        path: pugixml

    - name: Checkout nanosvg
      uses: actions/checkout@v4
      with:
        repository: memononen/nanosvg
        path: nanosvg

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: Pull build environment
      run: |
        docker pull ghcr.io/qnx-ports/sdp800-build-env:latest

    - name: Build EmulationStation
      uses: addnab/docker-run-action@v3
      with:
        image: ghcr.io/qnx-ports/sdp800-build-env:latest
        options: -v ${{ github.workspace }}:/home/runner/workspace -e MAKEFLAGS=${{ env.MAKEFLAGS }}
        shell: bash
        run: |
          source ~/qnx/800/qnxsdp-env.sh
          cd ~/workspace
          PREFIX="/usr/local" QNX_PROJECT_ROOT="$(pwd)/SDL" make -C build-files/ports/SDL install -j$(nproc)
          PREFIX="/usr/local" QNX_PROJECT_ROOT="$(pwd)/pugixml" make -C build-files/ports/pugixml install -j$(nproc)
          PREFIX="/usr/local" QNX_PROJECT_ROOT="$(pwd)/nanosvg" make -C build-files/ports/nanosvg install -j$(nproc)
          PREFIX="/usr/local" QNX_PROJECT_ROOT="$(pwd)/FreeImage" make -C build-files/ports/FreeImage install -j$(nproc)
          PREFIX="/usr/local" QNX_PROJECT_ROOT="$(pwd)/rapidjson" make -C build-files/ports/rapidjson install -j$(nproc)
          PREFIX="/usr/local" QNX_PROJECT_ROOT="$(pwd)/EmulationStation" make -C build-files/ports/RetroPie/EmulationStation install -j$(nproc)
