name: FreeImage

permissions:
  contents: write
  checks: write


on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/FreeImage.yml'
      - 'ports/FreeImage/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/FreeImage.yml'
      - 'ports/FreeImage/**'

jobs:

  build:
    strategy:
      matrix:
        qnx_env: [710, 800]
    name: Build for QNX ${{ matrix.qnx_env }}
    runs-on: ubuntu-22.04-common
    if: |
      ((github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'FreeImage')))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files

    - name: Checkout FreeImage
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/FreeImage
        path: FreeImage

    - name: Build FreeImage
      shell: bash
      run: |
        if [ "${{ matrix.qnx_env }}" == "710" ]; then
          source ~/qnx/710/qnxsdp-env.sh
        else
          source ~/qnx/800/qnxsdp-env.sh
        fi
        OSLIST="nto" QNX_PROJECT_ROOT="$(pwd)/FreeImage" make -C build-files/ports/FreeImage install 
