name: fribidi

permissions:
  contents: write
  checks: write

 
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/fribidi.yml'
      - 'ports/fribidi/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/fribidi.yml'
      - 'ports/fribidi/**'

jobs:
 
  build:
    runs-on: ubuntu-22.04-common
    if: |
      ((github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'fribidi')))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files

    - name: Checkout meson
      uses: actions/checkout@v4
      with:
        repository: mesonbuild/meson
        path: meson
 
    - name: Checkout fribidi
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/fribidi
        path: fribidi
 
    - name: Build fribidi
      shell: bash
      run: |
        source ~/qnx/800/qnxsdp-env.sh
        QNX_PROJECT_ROOT="$(pwd)/fribidi" make -C build-files/ports/fribidi/ JLEVEL=$(nproc) install
