name: gmp

permissions:
  contents: write
  checks: write


on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/gmp.yml'
      - 'ports/gmp/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/gmp.yml'
      - 'ports/gmp/**'

jobs:

  build:
    runs-on: ubuntu-22.04-common
    if: |
      ((github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'gmp')))
    steps:
      - name: Checkout build-files
        uses: actions/checkout@v4
        with:
          path: build-files

      - name: Download and extract GMP
        run: |
          cd ${{ github.workspace }}
          curl -L -o gmp-6.2.0.tar.xz https://gmplib.org/download/gmp/gmp-6.2.0.tar.xz
          tar -xvf gmp-6.2.0.tar.xz
          mv gmp-6.2.0 gmp

      - name: Build GMP
        shell: bash
        run: |
          if [[ "${{ matrix.qnx_env }}" == "800" ]]; then
            source ~/qnx/800/qnxsdp-env.sh
          else
            source ~/qnx/710/qnxsdp-env.sh
          fi
          JLEVEL=$(nproc) QNX_PROJECT_ROOT="$(pwd)/gmp" make -C build-files/ports/gmp install
