name: gmp

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/gmp.yml"
      - "ports/gmp/**"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/gmp.yml"
      - "ports/gmp/**"

jobs:
  build:
    strategy:
      matrix:
        qnx_env: ["710", "800"]
    name: Build for QNX ${{ matrix.qnx_env }}
    runs-on: self-hosted
    if: |
      (github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'gmp'))
    steps:
      - name: Checkout build-files
        uses: actions/checkout@v4
        with:
          path: build-files

      - name: Install wget
        run: |
          sudo apt-get update
          sudo apt-get install -y wget

      - name: Download and extract GMP
        run: |
          cd ${{ github.workspace }}
          wget https://gmplib.org/download/gmp/gmp-6.2.0.tar.xz
          tar -xvf gmp-6.2.0.tar.xz
          mv gmp-6.2.0 gmp

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Pull build environment
        run: |
          docker pull ghcr.io/qnx-ports/sdp-build-env:latest

      - name: Build GMP
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/qnx-ports/sdp-build-env:latest
          options: -v ${{ github.workspace }}:/home/runner/workspace -e MAKEFLAGS=${{ env.MAKEFLAGS }}
          shell: bash
          run: |
            if [[ ${{ matrix.qnx_env }} == 710 ]]; then
              source ~/qnx/710/qnxsdp-env.sh
            else
              source ~/qnx/800/qnxsdp-env.sh
            fi
            cd ~/workspace
            make -C build-files/ports/gmp install