name: graphite

permissions:
  contents: write
  checks: write

 
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/graphite.yml'
      - 'ports/graphite/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/graphite.yml'
      - 'ports/graphite/**'

jobs:
 
  build:
    strategy:
      matrix:
        qnx_env: ["710", "800"]
    name: Build for QNX ${{ matrix.qnx_env }}
    runs-on: ubuntu-22.04-common
    if: |
      ((github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'graphite')))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files
 
    - name: Checkout graphite
      uses: actions/checkout@v4
      with:
        repository: silnrsi/graphite
        path: graphite
        ref: 1.3.14
 
    - name: Build graphite
      shell: bash
      run: |
        if [ "${{ matrix.qnx_env }}" == "710" ]; then
          source ~/qnx/710/qnxsdp-env.sh
        else
          source ~/qnx/800/qnxsdp-env.sh
        fi
        QNX_PROJECT_ROOT="$(pwd)/graphite" JLEVEL=$(nproc) make -C build-files/ports/graphite install
