name: graphite
 
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/graphite.yml'
      - 'ports/graphite/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/graphite.yml'
      - 'ports/graphite/**'

jobs:
 
  build:
    runs-on: self-hosted
    if: |
      (github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'graphite'))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files
 
    - name: Checkout graphite
      uses: actions/checkout@v4
      with:
        repository: silnrsi/graphite
        path: graphite
        ref: 1.3.14
 
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
 
    - name: Pull build environment
      run: |
        docker pull ghcr.io/qnx-ports/sdp800-build-env:latest
 
    - name: Build graphite
      uses: addnab/docker-run-action@v3
      with:
        image: ghcr.io/qnx-ports/sdp800-build-env:latest
        options: -v ${{ github.workspace }}:/home/runner/workspace -e MAKEFLAGS=${{ env.MAKEFLAGS }}
        shell: bash
        run: |
          source ~/qnx/800/qnxsdp-env.sh
          cd ~/workspace
          QNX_PROJECT_ROOT="$(pwd)/graphite" JLEVEL=$(nproc) make -C build-files/ports/graphite install
