name: harfbuzz

permissions:
  contents: write
  checks: write

 
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/harfbuzz.yml'
      - 'ports/harfbuzz/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/harfbuzz.yml'
      - 'ports/harfbuzz/**'

jobs:
 
  build:
    strategy:
      matrix:
        qnx_env: ["710", "800"]
    name: Build for QNX ${{ matrix.qnx_env }}
    runs-on: ubuntu-22.04-common
    if: |
      ((github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'harfbuzz')))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files
 
    - name: Checkout harfbuzz
      uses: actions/checkout@v4
      with:
        repository: harfbuzz/harfbuzz
        path: harfbuzz
        ref: 10.2.0

    - name: Checkout meson
      uses: actions/checkout@v4
      with:
        repository: mesonbuild/meson
        path: meson
        ref: 1.7.0
 
    - name: Build harfbuzz
      shell: bash
      run: |
        if [[ ${{ matrix.qnx_env }} == 710 ]]; then
          source ~/qnx/710/qnxsdp-env.sh
        else
          source ~/qnx/800/qnxsdp-env.sh
        fi
        chmod +x build-files/ports/harfbuzz/install_all.sh
        JLEVEL=$(nproc) ./build-files/ports/harfbuzz/install_all.sh 
        JLEVEL=$(nproc) QNX_PROJECT_ROOT="$(pwd)/harfbuzz" make -C build-files/ports/harfbuzz install
