name: icu

permissions:
  contents: write
  checks: write

 
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/icu.yml'
      - 'ports/icu/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/icu.yml'
      - 'ports/icu/**'

jobs:
 
  build:
    strategy:
      matrix:
        qnx_env: ["710", "800"]
    name: Build for QNX ${{ matrix.qnx_env }}
    runs-on: ubuntu-22.04-common
    if: |
      ((github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'icu')))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files
 
    - name: Checkout icu
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/icu
        path: icu
 
    - name: Build icu
      shell: bash
      run: |
        if [ "${{ matrix.qnx_env }}" == "710" ]; then
          source ~/qnx/710/qnxsdp-env.sh
        else
          source ~/qnx/800/qnxsdp-env.sh
        fi
        QNX_PROJECT_ROOT="$(pwd)/icu" MAKE_BUILD_TEST=true JLEVEL=$(nproc) make -C build-files/ports/icu clean install
