name: kineto

permissions:
  contents: write
  checks: write


on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/kineto.yml'
      - 'ports/kineto/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/kineto.yml'
      - 'ports/kineto/**'

jobs:

  build:
    runs-on: ubuntu-22.04-common
    strategy:
      matrix:
        qnx_env: ["710", "800"]
    name: Build for QNX ${{ matrix.qnx_env }}
    if: |
      ((github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'kineto')))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files

    - name: Checkout kineto
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/kineto
        path: kineto
        ref: qnx_main
        submodules: recursive

    - name: Build kineto
      shell: bash
      run: |
        WORKSPACE=$PWD
        if [ "${{ matrix.qnx_env }}" == "710" ]; then
          source ~/qnx/710/qnxsdp-env.sh
        else
          source ~/qnx/800/qnxsdp-env.sh
        fi
        source /usr/local/qnx/env/bin/activate
        cd kineto && git submodule update --init --recursive
        cd $WORKSPACE
        QNX_PROJECT_ROOT="$(pwd)/kineto/libkineto" make -C build-files/ports/kineto install
