name: lely-core

permissions:
  contents: write
  checks: write


on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/lely-core.yml'
      - 'ports/lely-core/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/lely-core.yml'
      - 'ports/lely-core/**'

jobs:

  build:
    runs-on: ubuntu-22.04-common
    if: |
      ((github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'lely-core')))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files

    - name: Checkout lely-core
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/lely-core
        path: lely-core

    - name: Build lely-core
      shell: bash
      run: |
        source ~/qnx/800/qnxsdp-env.sh
        cd lely-core
        autoreconf -i
        cd -
        make -C build-files/ports/lely-core install
