name: libdrm

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/libdrm.yml'
      - 'ports/libdrm/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/libdrm.yml'
      - 'ports/libdrm/**'

jobs:

  build:
    runs-on: self-hosted
    strategy:
      matrix:
        qnx_env:
          - ghcr.io/qnx-ports/sdp800-build-env:latest
          - ghcr.io/qnx-ports/sdp-build-env:latest
    if: |
      (github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'libdrm'))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files

    - name: Checkout libdrm from GitLab
      run: |
        git clone https://gitlab.freedesktop.org/mesa/drm.git libdrm

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Pull build environment
      run: |
        docker pull ${{ matrix.qnx_env }}
    - name: Build libdrm
      uses: addnab/docker-run-action@v3
      with:
        image: ${{ matrix.qnx_env }}
        options: -v ${{ github.workspace }}:/home/runner/workspace -e MAKEFLAGS=${{ env.MAKEFLAGS }}
        shell: bash
        run: |
          cd workspace
          if [[ "${{ matrix.qnx_env}}" == "ghcr.io/qnx-ports/sdp800-build-env:latest" ]]; then
            source ~/qnx/800/qnxsdp-env.sh
          else 
            source ~/qnx/710/qnxsdp-env.sh
          fi
          DIST_ROOT=$(pwd)/drm make -C build-files/ports/libdrm/ install