name: libev

permissions:
  contents: write
  checks: write


on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/libev.yml"
      - "ports/libev/**"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/libev.yml"
      - "ports/libev/**"

jobs:

  build:
    strategy:
      matrix:
        qnx_env: ["710", "800"]
    runs-on: ubuntu-22.04-common
    if: |
      ((github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'libev')))
    steps:
      - name: Checkout build-files
        uses: actions/checkout@v4
        with:
          path: build-files

      - name: Checkout libev
        uses: actions/checkout@v4
        with:
          repository: qnx-ports/libev
          path: libev

      - name: Build libev
        shell: bash
        run: |
          if [[ ${{ matrix.qnx_env }} == 710 ]]; then
            source ~/qnx/710/qnxsdp-env.sh
          else
            source ~/qnx/800/qnxsdp-env.sh
          fi
          make -C build-files/ports/libev install
          
