name: libpng
 
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/libpng.yml'
      - 'ports/libpng/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/libpng.yml'
      - 'ports/libpng/**'

jobs:
 
  build:
    strategy:
      matrix:
        qnx_env:
          - ghcr.io/qnx-ports/sdp800-build-env:latest
          - ghcr.io/qnx-ports/sdp-build-env:latest
    runs-on: self-hosted
    if: |
      (github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'libpng'))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files
 
    - name: Checkout libpng
      uses: actions/checkout@v4
      with:
        repository: pnggroup/libpng
        path: libpng
        ref: v1.6.46
 
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
 
    - name: Pull build environment
      run: |
        docker pull ${{ matrix.qnx_env }}
 
    - name: Build libpng
      uses: addnab/docker-run-action@v3
      with:
        image: ${{ matrix.qnx_env }}
        options: -v ${{ github.workspace }}:/home/runner/workspace -e MAKEFLAGS=${{ env.MAKEFLAGS }}
        shell: bash
        run: |
          if [[ "${{ matrix.qnx_env}}" == "ghcr.io/qnx-ports/sdp800-build-env:latest" ]]; then
            source ~/qnx/800/qnxsdp-env.sh
          else 
            source ~/qnx/710/qnxsdp-env.sh
          fi
          cd workspace
          chmod +x build-files/ports/libpng/install_all.sh
          JLEVEL=$(nproc) ./build-files/ports/libpng/install_all.sh 
          JLEVEL=$(nproc) QNX_PROJECT_ROOT="$(pwd)/libpng" make -C build-files/ports/libpng install
