name: libthai

permissions:
  contents: write
  checks: write

 
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/libthai.yml'
      - 'ports/libthai/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/libthai.yml'
      - 'ports/libthai/**'

jobs:
 
  build:
    strategy:
      matrix:
        qnx_env: ["710", "800"]
    name: Build for QNX ${{ matrix.qnx_env }}
    runs-on: ubuntu-22.04-common
    if: |
      ((github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'libthai')))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files
 
    - name: Build libthai
      shell: bash
      run: |
        if [[ ${{ matrix.qnx_env }} == 710 ]]; then
          source ~/qnx/710/qnxsdp-env.sh
        else
          source ~/qnx/800/qnxsdp-env.sh
        fi
        wget https://linux.thai.net/pub/thailinux/software/libthai/libthai-0.1.29.tar.xz && tar -xf libthai-0.1.29.tar.xz
        chmod +x build-files/ports/libthai/install_all.sh
        JLEVEL=$(nproc) ./build-files/ports/libthai/install_all.sh 
        JLEVEL=$(nproc) QNX_PROJECT_ROOT="$(pwd)/libthai-0.1.29" make -C build-files/ports/libthai install
