name: libjpeg-turbo

permissions:
  contents: write
  checks: write

 
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/libjpeg-turbo.yml'
      - 'ports/libjpeg-turbo/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/libjpeg-turbo.yml'
      - 'ports/libjpeg-turbo/**'

jobs:
  build:
    strategy:
      matrix:
        qnx_env: [ 710, 800 ]
    runs-on: ubuntu-22.04-common
    if: |
      ((github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'libjpeg-turbo')))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files
 
    - name: Checkout libjpeg-turbo
      uses: actions/checkout@v4
      with:
        repository: libjpeg-turbo/libjpeg-turbo
        path: libjpeg-turbo
        ref: 3.1.0
 
    - name: Build libjpeg-turbo
      shell: bash
      run: |
        if [[ "${{ matrix.qnx_env}}" == "800" ]]; then
          source ~/qnx/800/qnxsdp-env.sh
        else 
          source ~/qnx/710/qnxsdp-env.sh
        fi
        JLEVEL=$(nproc) QNX_PROJECT_ROOT="$(pwd)/libjpeg-turbo" make -C build-files/ports/libjpeg-turbo install
