name: libyaml

permissions:
  contents: write
  checks: write


on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/libyaml.yml'
      - 'ports/libyaml/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/libyaml.yml'
      - 'ports/libyaml/**'

jobs:

  build:
    runs-on: ubuntu-22.04-common
    if: |
      ((github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'libyaml')))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files

    - name: Checkout libyaml
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/libyaml
        path: libyaml

    - name: Build libyaml
      shell: bash
      run: |
        source ~/qnx/800/qnxsdp-env.sh
        QNX_PROJECT_ROOT="$(pwd)/libyaml" make -C build-files/ports/libyaml install
