name: lighttpd1.4

permissions:
  contents: write
  checks: write


on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/lighttpd1.4.yml'
      - 'ports/lighttpd1.4/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/lighttpd1.4.yml'
      - 'ports/lighttpd1.4/**'

jobs:

  build:
    runs-on: ubuntu-22.04-common
    if: |
      ((github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'libghttp1.4')))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files

    - name: Checkout lighttpd1.4
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/lighttpd1.4
        path: lighttpd1.4

    - name: Build lighttpd1.4
      shell: bash
      run: |
        source ~/qnx/800/qnxsdp-env.sh
        cd lighttpd1.4
        ./autogen.sh
        cd -
        QNX_PROJECT_ROOT="$(pwd)/lighttpd1.4" make -C build-files/ports/lighttpd1.4 install 
