name: memory

permissions:
  contents: write
  checks: write


on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/memory.yml'
      - 'ports/memory/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/memory.yml'
      - 'ports/memory/**'

jobs:

  build:
    runs-on: ubuntu-22.04-common
    if: |
      ((github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'memory')))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files

    - name: Checkout memory
      uses: actions/checkout@v4
      with:
        repository: foonathan/memory
        path: memory

    - name: Build memory v0.7-3 (tag checkout does not work)
      shell: bash
      run: |
        source ~/qnx/800/qnxsdp-env.sh
        WORKSPACE=$PWD
        cd memory
        git checkout 0f07757
        cd $WORKSPACE
        patch memory/test/CMakeLists.txt < build-files/ports/memory/memory_0.7-3_patch.patch
        QNX_PROJECT_ROOT="$(pwd)/memory" make -C build-files/ports/memory install
