name: mosquitto

permissions:
  contents: write
  checks: write


on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/mosquitto.yml'
      - 'ports/mosquitto/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/mosquitto.yml'
      - 'ports/mosquitto/**'

jobs:

  build:
    runs-on: ubuntu-22.04-common
    if: |
      ((github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'mosquitto')))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files

    - name: Checkout mosquitto
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/mosquitto
        path: mosquitto

    - name: Build mosquitto
      shell: bash
      run: |
        source ~/qnx/800/qnxsdp-env.sh
        BUILD_TESTING="ON" QNX_PROJECT_ROOT="$(pwd)/mosquitto" make -C build-files/ports/mosquitto install 
