name: oneTBB

permissions:
  contents: write
  checks: write

 
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/oneTBB.yml'
      - 'ports/oneTBB/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/oneTBB.yml'
      - 'ports/oneTBB/**'

jobs:
 
  build:
    strategy:
      matrix:
        qnx_env: ["710", "800"]
    name: Build for QNX ${{ matrix.qnx_env }}
    runs-on: ubuntu-22.04-common
    if: |
      ((github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'oneTBB')))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files
 
    - name: Checkout oneTBB
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/oneTBB
        path: oneTBB
        ref: qnx-v2022.3.0-rc1
 
    - name: Build oneTBB
      shell: bash
      run: |
        if [ "${{ matrix.qnx_env }}" == "710" ]; then
          source ~/qnx/710/qnxsdp-env.sh
        else
          source ~/qnx/800/qnxsdp-env.sh
        fi
        make -C build-files/ports/oneTBB install
