name: pcre2
 
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/pcre2.yml'
      - 'ports/pcre2/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/pcre2.yml'
      - 'ports/pcre2/**'

jobs:
 
  build:
    strategy:
      matrix:
        qnx_env: ["710", "800"]
    name: Build for QNX ${{ matrix.qnx_env }}
    runs-on: self-hosted
    if: |
      (github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'pcre2'))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files
 
    - name: Checkout pcre2
      uses: actions/checkout@v4
      with:
        repository: PCRE2Project/pcre2
        path: pcre2
        ref: pcre2-10.45
 
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
 
    - name: Pull build environment
      run: |
        docker pull ghcr.io/qnx-ports/sdp-build-env:latest
 
    - name: Build pcre2
      uses: addnab/docker-run-action@v3
      with:
        image: ghcr.io/qnx-ports/sdp-build-env:latest
        options: -v ${{ github.workspace }}:/home/runner/workspace -e MAKEFLAGS=${{ env.MAKEFLAGS }}
        shell: bash
        run: |
          if [ "${{ matrix.qnx_env }}" == "710" ]; then
            source ~/qnx/710/qnxsdp-env.sh
          else
            source ~/qnx/800/qnxsdp-env.sh
          fi
          cd ~/workspace
          JLEVEL=$(nproc) QNX_PROJECT_ROOT="$(pwd)/pcre2" make -C build-files/ports/pcre2 install
