name: pcre2

permissions:
  contents: write
  checks: write

 
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/pcre2.yml'
      - 'ports/pcre2/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/pcre2.yml'
      - 'ports/pcre2/**'

jobs:
 
  build:
    strategy:
      matrix:
        qnx_env: [ 710, 800 ]
    runs-on: ubuntu-22.04-common
    if: |
      ((github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'pcre2')))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files
 
    - name: Checkout pcre2
      uses: actions/checkout@v4
      with:
        repository: PCRE2Project/pcre2
        path: pcre2
        ref: pcre2-10.45
 
    - name: Build pcre2
      shell: bash
      run: |
        if [[ "${{ matrix.qnx_env}}" == "800" ]]; then
          source ~/qnx/800/qnxsdp-env.sh
        else 
          source ~/qnx/710/qnxsdp-env.sh
        fi
        JLEVEL=$(nproc) QNX_PROJECT_ROOT="$(pwd)/pcre2" make -C build-files/ports/pcre2 install
