name: pdfium

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/pdfium.yml'
      - 'ports/pdfium/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/pdfium.yml'
      - 'ports/pdfium/**'

jobs:
  build:
    strategy:
      matrix:
        qnx_env: ["800"] 
    name: Build for QNX ${{ matrix.qnx_env }}
    runs-on: self-hosted
    if: |
      (github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'pdfium'))
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Pull build environment
      run: |
        docker pull ghcr.io/qnx-ports/sdp-build-env:latest

    - name: Parse branch name
      id: parse
      run: |
        if [[ "${{ github.head_ref }}" != '' ]]; then
          echo "branch=${GITHUB_HEAD_REF##*/}" >> $GITHUB_OUTPUT
        else
          echo "branch=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT GITHUB_REF
        fi

    - name: Build pdfium
      uses: addnab/docker-run-action@v3
      with:
        image: ghcr.io/qnx-ports/sdp-build-env:latest
        options: -v ${{ github.workspace }}:/home/runner/workspace -e MAKEFLAGS=${{ env.MAKEFLAGS }}
        shell: bash
        run: |
          # clone and sync pdfium
          if [[ ${{ matrix.qnx_env }} == 710 ]]; then
            source ~/qnx/710/qnxsdp-env.sh
          else
            source ~/qnx/800/qnxsdp-env.sh
          fi
          export PATH=/usr/local/qnx/depot_tools:$PATH
          cd workspace
          gclient config --unmanaged --custom-var checkout_qnx=True --custom-var qnx_build_files_branch=${{ steps.parse.outputs.branch }} https://github.com/qnx-ports/pdfium.git
          echo "target_os = [\"qnx\"]" >> .gclient
          gclient sync
          # Make
          cd pdfium
          make