name: pdfium

permissions:
  contents: write
  checks: write


on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/pdfium.yml'
      - 'ports/pdfium/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/pdfium.yml'
      - 'ports/pdfium/**'

jobs:
  build:
    strategy:
      matrix:
        qnx_env: ["800"] 
    name: Build for QNX ${{ matrix.qnx_env }}
    runs-on: ubuntu-22.04-common
    if: |
      ((github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'pdfium')))
    steps:
    - name: Parse branch name
      id: parse
      run: |
        if [[ "${{ github.head_ref }}" != '' ]]; then
          echo "branch=${GITHUB_HEAD_REF##*/}" >> $GITHUB_OUTPUT
        else
          echo "branch=main" >> $GITHUB_OUTPUT
        fi

    - name: Build pdfium
      shell: bash
      run: |
        # clone and sync pdfium
        if [[ ${{ matrix.qnx_env }} == 710 ]]; then
          source ~/qnx/710/qnxsdp-env.sh
        else
          source ~/qnx/800/qnxsdp-env.sh
        fi
        export PATH=/usr/local/qnx/depot_tools:$PATH
        gclient config --unmanaged --custom-var checkout_qnx=True --custom-var qnx_build_files_branch=${{ steps.parse.outputs.branch }} https://github.com/qnx-ports/pdfium.git
        echo "target_os = [\"qnx\"]" >> .gclient
        gclient sync
        # Make
        cd pdfium
        make
