name: pugixml

permissions:
  contents: write
  checks: write


on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/pugixml.yml'
      - 'ports/pugixml/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/pugixml.yml'
      - 'ports/pugixml/**'

jobs:
  build:
    strategy:
      matrix:
        qnx_env: [710, 800]
    name: Build for QNX ${{ matrix.qnx_env }}
    runs-on: ubuntu-22.04-common
    if: |
      ((github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'pugixml')))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files

    - name: Checkout pugixml
      uses: actions/checkout@v4
      with:
        repository: zeux/pugixml
        path: pugixml

    - name: Build pugixml
      shell: bash
      run: |
        if [ "${{ matrix.qnx_env }}" == "710" ]; then
          source ~/qnx/710/qnxsdp-env.sh
        else
          source ~/qnx/800/qnxsdp-env.sh
        fi
        PUGIXML_BUILD_TESTS=ON QNX_PROJECT_ROOT="$(pwd)/pugixml" make -C build-files/ports/pugixml install 
