name: re2

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/re2.yml'
      - 'ports/re2/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/re2.yml'
      - 'ports/re2/**'

jobs:

  build:
    runs-on: self-hosted
    if: |
      (github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 're2'))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files

    - name: Checkout googletest
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/googletest
        path: googletest

    - name: Checkout benchmark
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/benchmark
        path: benchmark

    - name: Checkout abseil-cpp
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/abseil-cpp
        path: abseil-cpp

    - name: Checkout muslflt
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/muslflt
        path: muslflt

    - name: Checkout re2
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/re2
        path: re2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Pull build environment
      run: |
        docker pull ghcr.io/qnx-ports/sdp800-build-env:latest

    - name: Build re2
      uses: addnab/docker-run-action@v3
      with:
        image: ghcr.io/qnx-ports/sdp800-build-env:latest
        options: -v ${{ github.workspace }}:/home/runner/workspace -e MAKEFLAGS=${{ env.MAKEFLAGS }}
        shell: bash
        run: |
          source ~/qnx/800/qnxsdp-env.sh
          cd ~/workspace
          BUILD_TESTING="OFF" QNX_PROJECT_ROOT="$(pwd)/googletest" make -C build-files/ports/googletest install 
          QNX_PROJECT_ROOT="$(pwd)/benchmark" make -C build-files/ports/benchmark install 
          QNX_PROJECT_ROOT="$(pwd)/muslflt" make -C build-files/ports/muslflt/ install 
          BUILD_TESTING="OFF" QNX_PROJECT_ROOT="$(pwd)/abseil-cpp" make -C build-files/ports/abseil-cpp install 
          OSLIST=nto QNX_PROJECT_ROOT="$(pwd)/re2" make -C build-files/ports/re2 install 
