name: rtl-sdr

permissions:
  contents: write
  checks: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/rtl-sdr.yml'
      - 'ports/rtl-sdr/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/rtl-sdr.yml'
      - 'ports/rtl-sdr/**'

jobs:
  build:
    strategy:
      matrix:
        qnx_env: [ 710, 800 ]
    runs-on: ubuntu-22.04-common
    if: |
      ((github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'rtl-sdr')))
    steps:
      - name: Checkout build-files
        uses: actions/checkout@v4
        with:
          path: build-files

      - name: Checkout rtl-sdr
        uses: actions/checkout@v4
        with:
          repository: qnx-ports/rtl-sdr
          ref: qnx_2.0.2
          path: rtl-sdr

      - name: Checkout libusb
        uses: actions/checkout@v4
        with:
          repository: qnx-ports/libusb
          ref: libusb-1.0.23
          path: libusb 

      - name: Build libusb
        shell: bash
        run: |
          if [[ "${{ matrix.qnx_env }}" == "800" ]]; then
            source ~/qnx/800/qnxsdp-env.sh
          else
            source ~/qnx/710/qnxsdp-env.sh
          fi
          QNX_PROJECT_ROOT="$(pwd)/libusb" make -C build-files/ports/libusb/ install

      - name: Build rtl-sdr
        shell: bash
        run: |
          if [[ "${{ matrix.qnx_env }}" == "800" ]]; then
            source ~/qnx/800/qnxsdp-env.sh
          else
            source ~/qnx/710/qnxsdp-env.sh
          fi
          QNX_PROJECT_ROOT="$(pwd)/rtl-sdr" make -C build-files/ports/rtl-sdr/ install
        