name: rtl-sdr

permissions:
  contents: write
  checks: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/rtl-sdr-stack.yml'
      - 'ports/rtl-sdr/**'
      - 'ports/libusb/**'
      
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/rtl-sdr-stack.yml'
      - 'ports/rtl-sdr/**'
      - 'ports/libusb/**'

jobs:
  build:
    strategy:
      matrix:
        qnx_env: ["710", "800"]

    name: Build rtl-sdr for QNX ${{ matrix.qnx_env }}
    runs-on: ubuntu-22.04-common
    if: |
      ((github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'rtl-sdr')))
      
    steps:
      - name: Checkout build-files
        uses: actions/checkout@v4
        with:
          path: build-files

      - name: Clone libusb
        run: |
          git clone https://github.com/qnx-ports/libusb.git

      - name: Build libusb
        shell: bash
        run: |
          if [[ "${{ matrix.qnx_env }}" == "800" ]]; then
            source ~/qnx/800/qnxsdp-env.sh
          else
            source ~/qnx/710/qnxsdp-env.sh
          fi
          QNX_PROJECT_ROOT="$(pwd)/libusb" make -C build-files/ports/libusb clean
          QNX_PROJECT_ROOT="$(pwd)/libusb" make -C build-files/ports/libusb install
          
      - name: Clone rtl-sdr
        run: |
          git clone https://github.com/qnx-ports/rtl-sdr.git

      - name: Build rtl-sdr
        shell: bash
        run: |
          if [[ "${{ matrix.qnx_env }}" == "800" ]]; then
            source ~/qnx/800/qnxsdp-env.sh
          else
            source ~/qnx/710/qnxsdp-env.sh
          fi
          QNX_PROJECT_ROOT="$(pwd)/rtl-sdr" make -C build-files/ports/rtl-sdr clean
          QNX_PROJECT_ROOT="$(pwd)/rtl-sdr" make -C build-files/ports/rtl-sdr install