name: rust

permissions:
  contents: write
  checks: write


on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/rust.yml'
      - 'ports/rust/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/rust.yml'
      - 'ports/rust/**'

jobs:

  build:
    runs-on: ubuntu-22.04-common
    if: |
      ((github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'rust')))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files

    - name: Checkout rust
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/rust
        path: rust

    - name: Build rust
      shell: bash
      run: |
        # install rustup
        curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y
        source ~/.cargo/env
        # build qnx8.0 targets
        source ~/qnx/800/qnxsdp-env.sh
        cat build-files/ports/rust/qnx800-config.toml > /rust/config.toml
        ./rust/x.py install
        rustup toolchain link qnx-800 rust/stage/host/linux/x86_64/usr/