name: s2n-tls

permissions:
  contents: write
  checks: write


on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/s2n-tls.yml"
      - "ports/s2n-tls/**"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/s2n-tls.yml"
      - "ports/s2n-tls/**"

jobs:
  build:
    strategy:
      matrix:
        qnx_env: ["710", "800"]
    name: Build for QNX ${{ matrix.qnx_env }}
    runs-on: ubuntu-22.04-common
    if: |
      ((github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 's2n-tls')))
    steps:
      - name: Checkout build-files
        uses: actions/checkout@v4
        with:
          path: build-files

      - name: Checkout s2n-tls
        uses: actions/checkout@v4
        with:
          repository: qnx-ports/s2n-tls
          path: s2n-tls

      - name: Build s2n-tls
        shell: bash
        run: |
          if [[ ${{ matrix.qnx_env }} == 710 ]]; then
            source ~/qnx/710/qnxsdp-env.sh
          else
            source ~/qnx/800/qnxsdp-env.sh
          fi
          make -C build-files/ports/s2n-tls install
