name: SDL

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/SDL.yml'
      - 'ports/SDL/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/SDL.yml'
      - 'ports/SDL/**'

jobs:

  build_205:
    runs-on: self-hosted
    if: |
      (github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && (contains(github.event.pull_request.title, 'SDL') || contains(github.event.pull_request.title, 'SDL')))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files

    - name: Checkout SDL
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/SDL
        path: SDL
        ref: qnx_2.0.5
    
    - name: Checkout googletest
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/googletest
        path: googletest

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: Pull build environment
      run: |
        docker pull ghcr.io/qnx-ports/sdp800-build-env:latest

    - name: Build SDL
      uses: addnab/docker-run-action@v3
      with:
        image: ghcr.io/qnx-ports/sdp800-build-env:latest
        options: -v ${{ github.workspace }}:/home/runner/workspace -e MAKEFLAGS=${{ env.MAKEFLAGS }}
        shell: bash
        run: |
          source ~/qnx/800/qnxsdp-env.sh
          cd ~/workspace
          PREFIX="/usr/local" QNX_PROJECT_ROOT="$(pwd)/SDL" make -C build-files/ports/SDL install -j$(nproc)

  build_2022:
    runs-on: self-hosted
    if: |
      (github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && (contains(github.event.pull_request.title, 'SDL') || contains(github.event.pull_request.title, 'SDL')))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files

    - name: Checkout SDL
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/SDL
        path: SDL
        ref: qnx_2.0.22
    
    - name: Checkout googletest
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/googletest
        path: googletest

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: Pull build environment
      run: |
        docker pull ghcr.io/qnx-ports/sdp800-build-env:latest

    - name: Build SDL
      uses: addnab/docker-run-action@v3
      with:
        image: ghcr.io/qnx-ports/sdp800-build-env:latest
        options: -v ${{ github.workspace }}:/home/runner/workspace -e MAKEFLAGS=${{ env.MAKEFLAGS }}
        shell: bash
        run: |
          source ~/qnx/800/qnxsdp-env.sh
          cd ~/workspace
          PREFIX="/usr/local" QNX_PROJECT_ROOT="$(pwd)/SDL" make -C build-files/ports/SDL install -j$(nproc)