name: SDL_ttf

permissions:
  contents: write
  checks: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/SDL_ttf.yml'
      - 'ports/SDL_ttf/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/SDL_ttf.yml'
      - 'ports/SDL_ttf/**'

jobs:

  build_205:
    strategy:
      matrix:
        qnx_env: [710, 800]
    name: Build for QNX ${{ matrix.qnx_env }}
    runs-on: ubuntu-22.04-common
    if: |
      ((github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'SDL_ttf')))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files

    - name: Checkout SDL_ttf
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/SDL_ttf
        path: SDL_ttf
        ref: qnx-release-2.0.18

    - name: Checkout SDL
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/SDL
        path: SDL
        ref: qnx-release-2.0.14

    - name: Build SDL_ttf
      shell: bash
      run: |
        if [ "${{ matrix.qnx_env }}" == "710" ]; then
          source ~/qnx/710/qnxsdp-env.sh
        else
          source ~/qnx/800/qnxsdp-env.sh
        fi
        PREFIX="usr/local" QNX_PROJECT_ROOT="$(pwd)/SDL_ttf" make -C build-files/ports/SDL_ttf install -j$(nproc)

