name: sleef

permissions:
  contents: write
  checks: write


on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/sleef.yml'
      - 'ports/sleef/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/sleef.yml'
      - 'ports/sleef/**'

jobs:

  build:
    runs-on: ubuntu-22.04-common
    if: |
      ((github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'sleef')))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files

    - name: Checkout sleef
      uses: actions/checkout@v4
      with:
        repository: shibatch/sleef
        path: sleef
        ref: 90ae01e5c71e378229ce0b2960a8e95dc89b9f17
        submodules: recursive

    - name: Build sleef
      shell: bash
      run: |
        WORKSPACE=$PWD
        source ~/qnx/800/qnxsdp-env.sh
        source /usr/local/qnx/env/bin/activate
        cd $WORKSPACE
        QNX_PROJECT_ROOT="$(pwd)/sleef" make -C build-files/ports/sleef install
