name: sqlite

permissions:
  contents: write
  checks: write

 
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/sqlite.yml'
      - 'ports/sqlite/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/sqlite.yml'
      - 'ports/sqlite/**'

jobs:
 
  build:
    strategy:
      matrix:
        qnx_env: ['710', '800']
    runs-on: ubuntu-22.04-common
    if: |
      ((github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'sqlite')))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files

    - name: Checkout sqlite
      uses: actions/checkout@v4
      with:
        repository: sqlite/sqlite
        path: sqlite
        ref: version-3.50.0
 
    - name: Build sqlite
      shell: bash
      run: |
        if [[ "${{ matrix.qnx_env}}" == "800" ]]; then
          source ~/qnx/800/qnxsdp-env.sh
        else 
          source ~/qnx/710/qnxsdp-env.sh
        fi
        QNX_PROJECT_ROOT="$(pwd)/sqlite" JLEVEL=$(nproc) make -C build-files/ports/sqlite clean install
