name: webrtc

permissions:
  contents: write
  checks: write


on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/webrtc.yml'
      - 'ports/webrtc/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/webrtc.yml'
      - 'ports/webrtc/**'

jobs:
  build:
    runs-on: ubuntu-22.04-common
    if: |
      ((github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'webrtc')))
    steps:
    - name: Parse branch name
      id: parse
      run: |
        if [[ "${{ github.head_ref }}" != '' ]]; then
          echo "branch=${GITHUB_HEAD_REF##*/}" >> $GITHUB_OUTPUT
        else
          echo "branch=main" >> $GITHUB_OUTPUT
        fi

    - name: Build webrtc
      shell: bash
      run: |
        # clone and sync webrtc
        source ~/qnx/710/qnxsdp-env.sh
        export PATH=/usr/local/qnx/depot_tools:$PATH
        gclient config --name=src --unmanaged --custom-var checkout_qnx=True --custom-var qnx_build_files_branch=${{ steps.parse.outputs.branch }} https://github.com/qnx-ports/webrtc.git
        echo "target_os = [\"qnx\"]" >> .gclient
        gclient sync
        # Make
        cd src
        make
        # Install
        make install
