name: XNNPACK

permissions:
  contents: write
  checks: write


on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/XNNPACK.yml'
      - 'ports/XNNPACK/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/XNNPACK.yml'
      - 'ports/XNNPACK/**'

jobs:

  build:
    runs-on: ubuntu-22.04-common
    if: |
      ((github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'XNNPACK')))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files

    - name: Checkout XNNPACK
      uses: actions/checkout@v4
      with:
        repository: qnx-ports/XNNPACK
        path: XNNPACK
        ref: qnx_master
        submodules: recursive

    - name: Build XNNPACK
      shell: bash
      run: |
        WORKSPACE=$PWD
        source ~/qnx/800/qnxsdp-env.sh
        source /usr/local/qnx/env/bin/activate
        cd $WORKSPACE
        QNX_PROJECT_ROOT="$(pwd)/XNNPACK" make -C build-files/ports/XNNPACK install
