name: zlib
 
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/zlib.yml'
      - 'ports/zlib/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/zlib.yml'
      - 'ports/zlib/**'

jobs:
 
  build:
    runs-on: self-hosted
    if: |
      (github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'zlib'))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files
 
    - name: Checkout zlib
      uses: actions/checkout@v4
      with:
        repository: madler/zlib
        path: zlib
        ref: v1.3.1
 
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
 
    - name: Pull build environment
      run: |
        docker pull ghcr.io/qnx-ports/sdp800-build-env:latest
 
    - name: Build zlib
      uses: addnab/docker-run-action@v3
      with:
        image: ghcr.io/qnx-ports/sdp800-build-env:latest
        options: -v ${{ github.workspace }}:/home/runner/workspace -e MAKEFLAGS=${{ env.MAKEFLAGS }}
        shell: bash
        run: |
          source ~/qnx/800/qnxsdp-env.sh
          cd ~/workspace
          JLEVEL=$(nproc) QNX_PROJECT_ROOT="$(pwd)/zlib" make -C build-files/ports/zlib install
