name: zlib

permissions:
  contents: write
  checks: write

 
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/zlib.yml'
      - 'ports/zlib/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/zlib.yml'
      - 'ports/zlib/**'

jobs:
 
  build:
    strategy:
      matrix:
        qnx_env: [ 710, 800 ]
    runs-on: ubuntu-22.04-common
    if: |
      ((github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'zlib')))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files
 
    - name: Checkout zlib
      uses: actions/checkout@v4
      with:
        repository: madler/zlib
        path: zlib
        ref: v1.3.1
 
    - name: Build zlib
      shell: bash
      run: |
        if [[ "${{ matrix.qnx_env}}" == "800" ]]; then
          source ~/qnx/800/qnxsdp-env.sh
        else 
          source ~/qnx/710/qnxsdp-env.sh
        fi
        JLEVEL=$(nproc) QNX_PROJECT_ROOT="$(pwd)/zlib" make -C build-files/ports/zlib install
